GET http://localhost:3000/messages

###
GET https://palindrome-project.herokuapp.com/messages

###
GET http://localhost:3000/messages/623e95e64b6bd1b978f39874


###
POST http://localhost:3000/messages/
Content-Type: application/json

{
    "userName": "Rishabh K",
    "messageBody": "wowow"
}
###
POST http://localhost:3000/messages/
Content-Type: application/json

{
    "userName": "Bruce Banner",
    "messageBody": "smash hsams"
}

###
DELETE http://localhost:3000/messages/623e95e64b6bd1b978f39874

###
PATCH http://localhost:3000/messages/623e95e64b6bd1b978f39874
Content-Type: application/json

{
    "messageBody": "lalalal"
}