GET http://localhost:3000/messages

###
GET https://palindrome-project.herokuapp.com/messages

###
GET http://localhost:3000/messages/623d677e06b753a5a5e0a2b8


###
POST http://localhost:3000/messages/
Content-Type: application/json

{
    "userName": "TEST USER 2",
    "messageBody": "madam"
}
###
POST http://localhost:3000/messages/
Content-Type: application/json

{
    "userName": "Bruce Banner",
    "messageBody": "smash hsams"
}

###
DELETE http://localhost:3000/messages/624161783e5b16615ee65147

###
PATCH http://localhost:3000/messages/62416f63d07d46eaf6f34431
Content-Type: application/json

{   "userName":"HI",
    "messageBody":"no madam"
}